services:
  db:
    env_file: .env
    ports:
      - 5432:5432
    image: postgres:alpine3.19
    restart: always
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./database/:/root/database/
